### ISSUE TITLE
Create A email based authentication in django

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#1]

**Comment by Abbas-Hussain-Muzammil** [comment]
Hey, I would love to solve this issue of creating an E-mail based authentication in Django...
I am very excited about this...

Can you assign this to me?

**Comment by belelaritra** [comment]
I would like to work on this issue as I have prior experience on the same.
Please assign this to me.

**Comment by RitikaSingh02** [comment]
I want to work on this issue under JWOC

**Comment by 7saikat7** [comment]
@RitikaSingh02  actually this issue has been divided into login and signup , so as u have first commented I can assign u the create a signup  (email base) instead . Hope it will work for you ?
