### ISSUE TITLE
improve readme.md

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#10]

**Comment by vivekjoshi-omni-pay** [comment]
Will improve readme.md

**Comment by NandiniAgrawal15** [comment]
I would like to work on it

**Comment by Geeky-Sam01** [comment]
Can I work on it?

**Comment by Shresa** [comment]
I want to work on this issue under JWOC

**Comment by 7saikat7** [comment]
@Shresa  please add a proper readme with logo , image of mentor, set up and all .Ping me on discord once,will provide the logo and image

**Comment by Shresa** [comment]
> Ok
