### ISSUE TITLE
add a .gitinore with different section for react , django , drf   add   how to set up project in readme.md resize the maninatiner image and make it almost like passport size 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#11]

**Comment by thatsuman** [comment]
Hi, can i work on this?
I saw some of the extensions are already there in `.gitignore`. so i need to add for others like react, drf etc. right?

**Comment by afreenabegum** [comment]
Hey @7saikat7 .Can you please assign it to me!!

Thank you.

**Comment by 7saikat7** [comment]
@afreenabegum  are you still available to take up this issue ?

**Comment by afreenabegum** [comment]
Yes am available, but can you tell me.. I just need to submit the document. Is it?

**Comment by 7saikat7** [comment]
yaa update gitignore , readme , add the installation and set up in read me , and make  my image smaller .Do msg me in community if necessary

**Comment by afreenabegum** [comment]
> yaa update gitignore , readme , add the installation and set up in read me , and make  my image smaller .Do msg me in community if necessary

Sorry for inconvenience, am not feeling well and busy with end sem exams.. It may take alot of time for me to solve this issue. Please you can assign it to someone else. 
Thank you

**Comment by 7saikat7** [comment]
if you want some more time  you can take or else will assign to someone else .

**Comment by afreenabegum** [comment]
please You can assign to someone else

**Comment by Atif0604** [comment]
hey @7saikat7 can you assign under JWOC
