### ISSUE TITLE
Ceate a signup feature using DRF

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#12]

**Comment by 7saikat7** [comment]
the email will be unique, auth will be email-based so keep it in mind .

**Comment by 7saikat7** [comment]
it will consist of name , company name , employee number [Dropdown : 1-10,11-5-,50-500,500-1000,1000+,company type[dropdown: personal , enterprise ,startup etc] and permissions made form custom user model

**Comment by SwastikPal1** [comment]
I want to work on this issue under JWOC

**Comment by SwastikPal1** [comment]
how much time do i have to complete the issue??

**Comment by RitikaSingh02** [comment]
@7saikat7 this issue is gd to go for me :) Kindly assign.

**Comment by r3yc0n1c** [comment]
I would like to work on this issue under JWOC'22

**Comment by 7saikat7** [comment]
Front end is not linked so if required go for a basic template an please test those api as well
