### ISSUE TITLE
Create a email based login system with DRF 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#13]

**Comment by Abbas-Hussain-Muzammil** [comment]
Can you share more about DRF?

**Comment by 7saikat7** [comment]
go for it !

**Comment by Abbas-Hussain-Muzammil** [comment]
Sure...

**Comment by 7saikat7** [comment]
any updates ?

**Comment by Abbas-Hussain-Muzammil** [comment]
I have got my end-semester exams...
I need some time to do this.

**Comment by 7saikat7** [comment]
ok let's see if anyone will it up or not then u have the issue

**Comment by sid-am-ahd935** [comment]
Is this a form based login system? Will it be using cookies or sessions? Can you provide some details?

**Comment by jayesh-shadi** [comment]
I want to work on this issue under JWOC

**Comment by 7saikat7** [comment]
Session based mentioned in group

**Comment by sid-am-ahd935** [comment]
Bhaiya can you assign me this issue? I will try to complete this issue.
