### ISSUE TITLE
create a Landing Page with a search bar 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#20]

**Comment by Arnab-batsy** [comment]
I'd like to work on this issue. Can you provide more details?

**Comment by 7saikat7** [comment]
you have to create a home page for the app as of now buid a ui as u want we will be sorting it out later .the home page will have a clean UI with a dropdown for links and a search bar so users can track with the tracking id

**Comment by 7saikat7** [comment]
who will grab it ?

**Comment by Arnab-batsy** [comment]
I'm in

**Comment by madhavchoudhary0911** [comment]
> who will grab it ?

I want to contribute to this issue under JWOC.

**Comment by 7saikat7** [comment]
what's the update ? time has exceded for PR please make a PR soon !

**Comment by abhiimali** [comment]
@7saikat7  Hello sir I Have Basic landing Page Should I Send A Pull Request Of Assigned Member Is Not Able To Do It In Time ?

![image](https://user-images.githubusercontent.com/55556198/152866287-0312328c-670c-488c-89a4-a1fe7996baaa.png)

**Comment by 7saikat7** [comment]
@abhiimali 
good work , got the pr merged it
