### ISSUE TITLE
Create the website's  UI using Figma  || Part 1

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#22]
please create a UI using Figma for more info consider asking in discord channels

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC.

**Comment by 7saikat7** [comment]
Hey what's the updated

**Comment by codervivek5** [comment]
in replacement of the issue #7 ....i am working in issue #8

**Comment by codervivek5** [comment]
this is completed or not

**Comment by codervivek5** [comment]
tell me plz
