### ISSUE TITLE
Create Signup page as per website figma design 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#43]
https://www.figma.com/file/1JMyodDjCK4SkiqXzHzkDK/Ship-It?node-id=0%3A1

**Comment by Ankit62042** [comment]
I want to work on this issue

**Comment by 7saikat7** [comment]
You already have 2 issues... So can't assign you more issue as of now .. please complete then first

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC

**Comment by Urstrulysuvangi** [comment]
Hey, here from SSOC-2022. May I work on this issue?

**Comment by 7saikat7** [comment]
sure

**Comment by Urstrulysuvangi** [comment]
Due to some unforeseen reasons, I'll have to unassign myself from this issue. My deepest, sincerest apologies for the inconvenience caused.

**Comment by 7saikat7** [comment]
okk

**Comment by Kritika0035** [comment]
May I work on this issue ?

**Comment by Rushijaviya** [comment]
Assigning this to you @Kritika0035. Go ahead!

**Comment by Kritika0035** [comment]
@Rushijaviya I have written the HTML code, so should I merge it today or after completing it??

**Comment by Rushijaviya** [comment]
> @Rushijaviya I have written the HTML code, so should I merge it today or after completing it??

Complete the task and then send pr.

**Comment by Rushijaviya** [comment]
#91 and #92
