### ISSUE TITLE
Create The Feature Of Adding Shipping Details 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#48]
1.Create routes for adding shipment data 
2.create database tables 
3. create adding functionality on them

* UI is available on Figma check it once , specially the dashboard section .Let me know about any doubts in the community

**Comment by RyanWalker277** [comment]
I would adore working on this problem. If you could give it to me, that would be fantastic.

**Comment by 7saikat7** [comment]
Hey ! thanks for showing interest, but this project is under SSOC, so I won't be able to assign you sorry!

**Comment by RyanWalker277** [comment]
> Hey ! thanks for showing interest, but this project is under SSOC, so I won't be able to assign you sorry!

Actually I am a participant of SSOC.I was browsing through the projects listed on the website and really liked the concept of this project.I would love to work on this feature under the SSOC hood.Can you please assign this to me when the contribution starts at SSOC? I would be really grateful

**Comment by 7saikat7** [comment]
Sure mam !
