### ISSUE TITLE
Create Pricing Page

### ISSUE THREAD

**Issue by codervivek5** [7saikat7/supply_chain#55]
I have created this page using Figma design.

**Comment by codervivek5** [comment]
@7saikat7 plz checkout my PR. this is created with the reference of Figma.

**Comment by codervivek5** [comment]
![image](https://user-images.githubusercontent.com/62784060/157501161-776b18ab-f0ed-41df-9289-bc73bd7a92ca.png)
 This is the output of our design.

**Comment by Urstrulysuvangi** [comment]
May I please work on this issue?

**Comment by Rushijaviya** [comment]
Assigning this to you @Urstrulysuvangi. Happy contributing!

**Comment by Urstrulysuvangi** [comment]
Hey @Rushijaviya I have just created a PR, can you please review it and let me know the changes to be done, if any. Thank You.

PR - #93

**Comment by Rushijaviya** [comment]
#93
