### ISSUE TITLE
Create Landing Pagefor the website as per figma design add a search bar too 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#59]
https://www.figma.com/file/1JMyodDjCK4SkiqXzHzkDK/Ship-It?node-id=0%3A1

**Comment by SardarShubham** [comment]
I can work on this, please assign this issue to me.

**Comment by 7saikat7** [comment]
sure

**Comment by 7saikat7** [comment]
hey it's been a long, No update, please raise a PR by tomorrow or else have to unassign you !
