### ISSUE TITLE
Create add delivery feature 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#61]
it will be linked to the a particular user , keep check to make it a delivery point

**Comment by 7saikat7** [comment]
create database model , URL , links and render raw HTML  just to show it's working

**Comment by akhil484** [comment]
Hey, I would like to work on it and maybe have some discussion about it.

**Comment by 7saikat7** [comment]
sure ping me or any mentor in our private channel

**Comment by 7saikat7** [comment]
Hey I am looking for a PR  it's already should be there

**Comment by ChucklesDroid** [comment]
can I work on this issue?

**Comment by 7saikat7** [comment]
hey please let me know that you have already worked on this issue? or yet to be assigned ??

**Comment by akhil484** [comment]
I worked on this issue, but my PR failed a test case. So, I am trying to fix it.

**Comment by vruddhideveloper** [comment]
I would like to work on this issue @Rushijaviya @7saikat7 ..Please assign this issue to me!

**Comment by Rushijaviya** [comment]
> I would like to work on this issue @Rushijaviya @7saikat7 ..Please assign this issue to me!

this issue is assigned to another person. You can work on #46 if you want.
