### ISSUE TITLE
Create Screens For Forgot password , verification mail send ,email verified 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#62]
Take help from Figma and create the rest of the pages

**Comment by nalin-singh** [comment]
I would like to work on this issue, for SSOC 22

**Comment by vruddhideveloper** [comment]
I would like to work on this issue @Rushijaviya @7saikat7 ..Please assign this issue to me!

**Comment by Rushijaviya** [comment]
> I would like to work on this issue @Rushijaviya @7saikat7 ..Please assign this issue to me!

this issue is already assigned to someone. You can choose another issue.

**Comment by ankur0904** [comment]
Can I  work on this issue?

**Comment by Rushijaviya** [comment]
Yes. You can, assigning this to you @ankur0904
