### ISSUE TITLE
R &D on how we can impletemt the feature of calculating the distance based on pin code and apply it 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#64]

**Comment by guptaaryan16** [comment]
Hey I want to take this issue, I might use an api to fetch the location based on pin code and then use it to find geo-coordinates to find distance

**Comment by 7saikat7** [comment]
please go ahead !

**Comment by chakradhar4** [comment]
Hey i want to take this issue

**Comment by 7saikat7** [comment]
@guptaaryan16 any info or progress please share it on discord!  it's been a week now

**Comment by guptaaryan16** [comment]
Hey just working on the issue, need a day to make PR
