### ISSUE TITLE
Dynamic Dashboar For Users

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#7]

**Comment by codervivek5** [comment]
I will design the attractive user friendly dashboard.

**Comment by 7saikat7** [comment]
as of now you can create it with html css , js also

**Comment by codervivek5** [comment]
Hey @7saikat7  There have any reference dashboard like figma design or make it own learning

**Comment by 7saikat7** [comment]
you have to make a code for the dashboard ! using Html,css ,js
