### ISSUE TITLE
Customize Django User Modle to implement different type of user eg:small business,enterprise, nano business 

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#70]
so we can use this role-based authentication feature to apply multi-user-based features and services.

**Comment by ChucklesDroid** [comment]
can I work on this issue ?

**Comment by 7saikat7** [comment]
sure

**Comment by 7saikat7** [comment]
please complete your previous issues, as discussed you can have 2 issues at a time .

**Comment by ChucklesDroid** [comment]
I have implemented one of those issues through PR. So right now I am only working on only one ( email verification )

**Comment by ChucklesDroid** [comment]
I have completed the Contact Us feature through PR
![image](https://user-images.githubusercontent.com/71250179/183306833-edefdb0e-f915-4c4c-9c26-8ccb7715ffaa.png)

**Comment by Srishti-Ahuja** [comment]
Can I take this up?

**Comment by 7saikat7** [comment]
@ChucklesDroid  please complete your auth feature using email

**Comment by 7saikat7** [comment]
@Srishti-Ahuja please create this feature and also keep in mind that it will be an email-based authentication

**Comment by ChucklesDroid** [comment]
@7saikat7 Yes I will try my best to make the pr today just working on few bugs right now
