### ISSUE TITLE
create basic structure and landing page In App for the project [Flutter]

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#71]

**Comment by yk3066** [comment]
I would like to work on this issue. Please assign it to me as part of ssoc.

**Comment by 7saikat7** [comment]
what's the status @yk3066 ??

**Comment by yk3066** [comment]
Had to work a bit on the splash screen since the image kept getting pixelated, it's fixed will move on to further pages.
https://user-images.githubusercontent.com/59407464/185738773-ef36ba72-6854-4f95-9293-169541aae5ae.mp4

**Comment by yk3066** [comment]
https://user-images.githubusercontent.com/59407464/185751543-1eaf494a-07ee-42a7-adff-8733398dafa8.mp4

**Comment by yk3066** [comment]
All basic structures made as per the given figma designs.

https://user-images.githubusercontent.com/59407464/186733109-8fa21d29-6e73-493b-8ba5-84db140b4409.mp4

**Comment by yk3066** [comment]
I need to push the flutter app. Which branch should i make my commit?

**Comment by 7saikat7** [comment]
android-build

**Comment by yk3066** [comment]
it says i don't have permission to push to this repo
