### ISSUE TITLE
Create Contact Us Page More Creative and Responsive

### ISSUE THREAD

**Issue by Divesh2003** [7saikat7/supply_chain#72]

**Comment by akanksha0812** [comment]
Please assign this to me! I know the implementation

**Comment by 7saikat7** [comment]
sure go for it

**Comment by 7saikat7** [comment]
please make a pr by tomorrow or else I have to unassign you !

**Comment by SardarShubham** [comment]
I can do it, please assign it to me.

**Comment by Divesh2003** [comment]
@SardarShubham Assigned to you
