### ISSUE TITLE
Create Login Page Responsive and Creative with Transistions

### ISSUE THREAD

**Issue by Divesh2003** [7saikat7/supply_chain#73]

**Comment by agr1ms** [comment]
Hello Sir!

I want to work on this issue

**Comment by agr1ms** [comment]
Please assign me this...
And also please guide me on where can I find the code of the Login page

**Comment by Divesh2003** [comment]
https://github.com/7saikat7/supply_chain/tree/frontend/Frontend/pages/

**Comment by agr1ms** [comment]
Made a PR... creating another for responsiveness

**Comment by Rushijaviya** [comment]
#81

**Comment by Rushijaviya** [comment]
@Agrim-Sharma174, what's the update? is it completed?
