### ISSUE TITLE
add homepage design(html/static file) and make the home page functional

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#78]
All the design is on the frontend branch please make the feature for home page of the website functional .[link the front end pages with backend django templates]

**Comment by ChucklesDroid** [comment]
can I work on this issue ?

**Comment by 7saikat7** [comment]
hey what's the update , please raise a PR asap

**Comment by ChucklesDroid** [comment]
yeah I am working on it and will raise the PR by tomorrow hopefully

**Comment by Rushijaviya** [comment]
closed with pr #89
