### ISSUE TITLE
Create easy to use app UI

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#8]

**Comment by codervivek5** [comment]
I will customise this UI as the community wan.I wil make different types of attractive UI for the project

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by 7saikat7** [comment]
will assign you @codervivek5  for sure let's first solve the issue #21

**Comment by codervivek5** [comment]
Ok i will make it easy to use.

**Comment by codervivek5** [comment]
I will make it using Figma?

**Comment by codervivek5** [comment]
> will assign you @codervivek5 for sure let's first solve the issue #21
Which type wee made UI for mobile App or website.

**Comment by codervivek5** [comment]
I have some question...i will make it home page design or more pages ?

**Comment by codervivek5** [comment]
I have some question...i will make it home page design or more pages ?

**Comment by codervivek5** [comment]
How i will share the file?

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC.

Do I need to do something in Flutter or Dart . If yes then please Don't assign it.
I want to work on this issue just because I'm a UI/UX designer.
