### ISSUE TITLE
Create less interactive pages with HTML , CSS , JS etc.

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#9]

**Comment by vivekjoshi-omni-pay** [comment]
Will work on it

**Comment by Rikky10** [comment]
Can I work on it?

**Comment by codervivek5** [comment]
I can customise it.I will make changes in the project in front side.

**Comment by Abbas-Hussain-Muzammil** [comment]
Hey, I would like to solve this...
Can you assign me?

**Comment by Geeky-Sam01** [comment]
Please, Assign it to me.

**Comment by NandiniAgrawal15** [comment]
Can I work on it

**Comment by abhiimali** [comment]
please assign it To Me If Possible ?

**Comment by 7saikat7** [comment]
As the coding phase will start from 1st Feb, will assign all the issues to the person who will comment on issues, on or before coding phase starts as per the rule of JGEC.

**Comment by 7saikat7** [comment]
This works for all the issues, please follow the discord community to get updates!

**Comment by Abbas-Hussain-Muzammil** [comment]
Please assign me...

**Comment by abhiimali** [comment]
@7saikat7  
"I want to work on this issue under JWOC"

**Comment by 7saikat7** [comment]
as per the starting phase @Abbas-Hussain-Muzammil, we are allowing 1 issue at a time to distribute the issue equally so I am transferring the issue to @abhiimali

**Comment by abhiimali** [comment]
Thank you for assignment !

**Comment by Arnab-batsy** [comment]
I'd like to work on this issue.

**Comment by abhiimali** [comment]
Hello Sir @7saikat7  Sorry  I Failed To Develop Pages Using React .  You Can Assign It To @Arnab-batsy

**Comment by 7saikat7** [comment]
ok but it's mention to use html,css js

**Comment by 7saikat7** [comment]
I am expecting a PR  by tomorrow or else will have to unassign you !

**Comment by KushalGhosh9899** [comment]
Hey I want to work on this issue under JWOC, can you give me some descriptions about what pages do I have to build?

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC @7saikat7

**Comment by KushalGhosh9899** [comment]
I already got assigned 2 issues so that's why I am unassigning myself so that other potential candidates can work on this issue

**Comment by codervivek5** [comment]
I can do it...you may assign this issue

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC @7saikat7

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC @7saikat7

**Comment by 7saikat7** [comment]
no update from @codervivek5

**Comment by codervivek5** [comment]
I want to work on this issue...by the exam issue, I was not doing any work...sorry for that but now I am free so I want to work on it plz assign it me

**Comment by codervivek5** [comment]
Can we make design with reference with Figma Design?

**Comment by codervivek5** [comment]
@7saikat7  I have create a landing page...just check out ..than I make a PR.

**Comment by codervivek5** [comment]
![image](https://user-images.githubusercontent.com/62784060/157446423-457ba122-929a-419d-b45f-41abedabf396.png)
I will make it with the reference of Figma.

**Comment by Urstrulysuvangi** [comment]
Hey found your project from the SSOC-2022 discord channel. I'd love to work on this issue. Could you please provide a little more detail regarding what pages are required to be built and their design scheme if any? Thank you.

**Comment by 7saikat7** [comment]
Hi,
Thanks for showing interest in this project.
Will assign and share everything about the project when the contribution
phase will start.We will also be having a meeting with all the participants
regarding the project.

**Comment by Urstrulysuvangi** [comment]
> 

Okay, that's great! Thank You.
